# Generated by Django 6.0 on 2026-03-30 14:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ('student__student_id',)},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('-date', '-start_time')},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('student_id',)},
        ),
        migrations.AddField(
            model_name='session',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api.session'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late')], default='PRESENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api.student'),
        ),
        migrations.AlterField(
            model_name='session',
            name='section',
            field=models.CharField(choices=[('WMD-1A', 'WMD-1A'), ('WMD-1B', 'WMD-1B'), ('WMD-1C', 'WMD-1C'), ('WMD-2A', 'WMD-2A'), ('WMD-2B', 'WMD-2B'), ('WMD-2C', 'WMD-2C'), ('BSIT-3A', 'BSIT-3A'), ('BSIT-3B', 'BSIT-3B'), ('BSIT-4A', 'BSIT-4A'), ('BSIT-4B', 'BSIT-4B')], max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_code',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_in_end',
            field=models.TimeField(help_text='Late threshold'),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_out_start',
            field=models.TimeField(verbose_name='Time out'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('WMD-1A', 'WMD-1A'), ('WMD-1B', 'WMD-1B'), ('WMD-1C', 'WMD-1C'), ('WMD-2A', 'WMD-2A'), ('WMD-2B', 'WMD-2B'), ('WMD-2C', 'WMD-2C'), ('BSIT-3A', 'BSIT-3A'), ('BSIT-3B', 'BSIT-3B'), ('BSIT-4A', 'BSIT-4A'), ('BSIT-4B', 'BSIT-4B')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'session'), name='unique_attendance_per_session'),
        ),
    ]
